<?php
	function get_CarName($model)
	{
		if($model==400) return 'Landstalker';
		elseif($model==401) return 'Bravura';
		elseif($model==402) return 'Buffalo';
		elseif($model==403) return 'Linerunner';
		elseif($model==404) return 'Perenniel';
		elseif($model==405) return 'Sentinel';
		elseif($model==406) return 'Dumper';
		elseif($model==407) return 'Firetruck';
		elseif($model==408) return 'Trashmaster';
		elseif($model==409) return 'Stretch';
		elseif($model==410) return 'Manana';
		elseif($model==411) return 'Infernus';
		elseif($model==412) return 'Voodoo';
		elseif($model==413) return 'Pony';
		elseif($model==414) return 'Mule';
		elseif($model==415) return 'Cheetah';
		elseif($model==416) return 'Ambulance';
		elseif($model==417) return 'Leviathan';
		elseif($model==418) return 'Moonbeam';
		elseif($model==419) return 'Esperanto';
		elseif($model==420) return 'Taxi';
		elseif($model==421) return 'Washington';
		elseif($model==422) return 'Bobcat';
		elseif($model==423) return 'Mr Whoopee';
		elseif($model==424) return 'BF Injection';
		elseif($model==425) return 'Hunter';
		elseif($model==426) return 'Premier';
		elseif($model==427) return 'Enforcer';
		elseif($model==428) return 'Securicar';
		elseif($model==429) return 'Banshee';
		elseif($model==430) return 'Predator';
		elseif($model==431) return 'Bus';
		elseif($model==432) return 'Rhino';
		elseif($model==433) return 'Barracks';
		elseif($model==434) return 'Hotknife';
		elseif($model==435) return 'Trailers';
		elseif($model==436) return 'Previon';
		elseif($model==437) return 'Coach';
		elseif($model==438) return 'Cabbie';
		elseif($model==439) return 'Stallion';
		elseif($model==440) return 'Rumpo';
		elseif($model==441) return 'RC Bandit';
		elseif($model==442) return 'Romero';
		elseif($model==443) return 'Packer';
		elseif($model==444) return 'Monster';
		elseif($model==445) return 'Admiral';
		elseif($model==446) return 'Squallo';
		elseif($model==447) return 'Seasparrow';
		elseif($model==448) return 'Pizzaboy';
		elseif($model==449) return 'Tram';
		elseif($model==450) return 'Trailers';
		elseif($model==451) return 'Turismo';
		elseif($model==452) return 'Speeder';
		elseif($model==453) return 'Reefer';
		elseif($model==454) return 'Tropic';
		elseif($model==455) return 'Flatbed';
		elseif($model==456) return 'Yankee';
		elseif($model==457) return 'Caddy';
		elseif($model==458) return 'Solair';
		elseif($model==459) return 'Topfun Van';
		elseif($model==460) return 'Skimmer';
		elseif($model==461) return 'PCJ-600';
		elseif($model==462) return 'Faggio';
		elseif($model==463) return 'Freeway';
		elseif($model==464) return 'RC Baron';
		elseif($model==465) return 'RC Raider';
		elseif($model==466) return 'Glendale';
		elseif($model==467) return 'Oceanic';
		elseif($model==468) return 'Sanchez';
		elseif($model==469) return 'Sparrow';
		elseif($model==470) return 'Patriot';
		elseif($model==471) return 'Quad';
		elseif($model==472) return 'Coastguard';
		elseif($model==473) return 'Dinghy';
		elseif($model==474) return 'Hermes';
		elseif($model==475) return 'Sabre';
		elseif($model==476) return 'Rustler';
		elseif($model==477) return 'ZR-350';
		elseif($model==478) return 'Walton';
		elseif($model==479) return 'Regina';
		elseif($model==480) return 'Comet';
		elseif($model==481) return 'BMX';
		elseif($model==482) return 'Burrito';
		elseif($model==483) return 'Camper';
		elseif($model==484) return 'Marquis';
		elseif($model==485) return 'Baggage';
		elseif($model==486) return 'Dozer';
		elseif($model==487) return 'Maverick';
		elseif($model==488) return 'SAN News Maverick';
		elseif($model==489) return 'Rancher';
		elseif($model==490) return 'FBI Rancher';
		elseif($model==412) return 'Virgo';
		elseif($model==492) return 'Greenwood';
		elseif($model==493) return 'Jetmax';
		elseif($model==494) return 'Hotring Racer';
		elseif($model==495) return 'Sandking';
		elseif($model==496) return 'Blista';
		elseif($model==497) return 'Police Maverick';
		elseif($model==498) return 'Boxville';
		elseif($model==499) return 'Benson';
		elseif($model==500) return 'Mesa';
		elseif($model==501) return 'RC Goblin';
		elseif($model==502) return 'Hotring Racer';
		elseif($model==503) return 'Hotring Racer';
		elseif($model==504) return 'Bloodring Banger';
		elseif($model==505) return 'Rancher';
		elseif($model==506) return 'Super GT';
		elseif($model==507) return 'Elegant';
		elseif($model==508) return 'Journey';
		elseif($model==509) return 'Bike';
		elseif($model==510) return 'Mountain Bike';
		elseif($model==511) return 'Beagle';
		elseif($model==512) return 'Cropduster';
		elseif($model==513) return 'Stuntplane';
		elseif($model==514) return 'Tanker';
		elseif($model==515) return 'Roadtrain';
		elseif($model==516) return 'Nebula';
		elseif($model==517) return 'Majestic';
		elseif($model==518) return 'Buccaneer';
		elseif($model==519) return 'Shamal';
		elseif($model==520) return 'Hydra';
		elseif($model==521) return 'FCR-900';
		elseif($model==522) return 'NRG-500';
		elseif($model==523) return 'HPV1000';
		elseif($model==524) return 'Cement Truck';
		elseif($model==525) return 'Towtruck';
		elseif($model==526) return 'Fortune';
		elseif($model==527) return 'Cadrona';
		elseif($model==528) return 'FBI Truck';
		elseif($model==529) return 'Willard';
		elseif($model==530) return 'Forklift';
		elseif($model==531) return 'Tractor';
		elseif($model==532) return 'Combine Harvester';
		elseif($model==533) return 'Feltzer';
		elseif($model==534) return 'Remington';
		elseif($model==535) return 'Slamvan';
		elseif($model==536) return 'Blade';
		elseif($model==537) return 'Freight';
		elseif($model==538) return 'Brownstreak';
		elseif($model==539) return 'Vortex';
		elseif($model==540) return 'Vincent';
		elseif($model==541) return 'Bullet';
		elseif($model==542) return 'Clover';
		elseif($model==543) return 'Sadler';
		elseif($model==544) return 'Firetruck';
		elseif($model==545) return 'Hustler';
		elseif($model==546) return 'Intruder';
		elseif($model==547) return 'Primo';
		elseif($model==548) return 'Cargobob';
		elseif($model==549) return 'Tampa';
		elseif($model==550) return 'Sunrise';
		elseif($model==551) return 'Merit';
		elseif($model==552) return 'Utility Van';
		elseif($model==553) return 'Nevada';
		elseif($model==554) return 'Yosemite';
		elseif($model==555) return 'Windsor';
		elseif($model==556) return 'Monster';
		elseif($model==557) return 'Monster';
		elseif($model==558) return 'Uranus';
		elseif($model==559) return 'Jester';
		elseif($model==560) return 'Sultan';
		elseif($model==561) return 'Stratum';
		elseif($model==562) return 'Elegy';
		elseif($model==563) return 'Raindance';
		elseif($model==564) return 'RC Tiger';
		elseif($model==565) return 'Flash';
		elseif($model==566) return 'Tahoma';
		elseif($model==567) return 'Savanna';
		elseif($model==568) return 'Bandito';
		elseif($model==569) return 'Trailers';
		elseif($model==570) return 'Trailers';
		elseif($model==571) return 'Kart';
		elseif($model==572) return 'Mower';
		elseif($model==573) return 'Dune';
		elseif($model==574) return 'Sweeper';
		elseif($model==575) return 'Broadway';
		elseif($model==576) return 'Tornado';
		elseif($model==577) return 'AT400';
		elseif($model==578) return 'DFT-30';
		elseif($model==579) return 'Huntley';
		elseif($model==580) return 'Stafford';
		elseif($model==581) return 'BF-400';
		elseif($model==582) return 'Newsvan';
		elseif($model==583) return 'Tug';
		elseif($model==584) return 'Trailer';
		elseif($model==585) return 'Emperor';
		elseif($model==586) return 'Wayfarer';
		elseif($model==587) return 'Euros';
		elseif($model==588) return 'Hotdog';
		elseif($model==589) return 'Club';
		elseif($model==590) return 'Trailer';
		elseif($model==591) return 'Trailer';
		elseif($model==592) return 'Andromada';
		elseif($model==593) return 'Dodo';
		elseif($model==594) return 'RC Cam';
		elseif($model==595) return 'Launch';
		elseif($model==596) return 'Police Car';
		elseif($model==597) return 'Police Car';
		elseif($model==598) return 'Police Car';
		elseif($model==599) return 'Police Ranger';
		elseif($model==601) return 'Picador';
		elseif($model==601) return 'S.W.A.T';
		elseif($model==602) return 'Alpha';
		elseif($model==603) return 'Phoenix';
		elseif($model==604) return 'Glendale Shit';
		elseif($model==605) return 'Sadler Shit';
		elseif($model==606) return 'Baggage';
		elseif($model==607) return 'Baggage';
		elseif($model==608) return 'Tug Stairs';
		elseif($model==609) return 'Boxville';
		elseif($model==610) return 'Farm Trailer';
		elseif($model==611) return 'Utility Trailer';
	}
?>